#################################################################
# Example render.yaml                                           #
# This file contains configuration for Render services.         #
#################################################################

# Enable preview environments
previews:
  generation: automatic

# List all services here except databases
services:
  # Web service for Node.js application with Playwright
  - type: web
    name: playwright-web
    env: node
    repo: 'https://github.com/Thunganrm/updateavailableroom/' # Repo chứa mã nguồn của bạn
    buildCommand: |
      npm install
      npx playwright install # Cài đặt Playwright
    startCommand: node server.js # Lệnh khởi động ứng dụng của bạn
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 60 # Điều chỉnh mức độ sử dụng CPU (từ 1 đến 90)
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/playwright # Đảm bảo Playwright biết đường dẫn trình duyệt
    healthCheckPath: /
    region: oregon

  # Web service for Python Flask app (main.py)
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "python app.py"
    port: 10000  # Hoặc sử dụng PORT từ môi trường

    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 60
    healthCheckPath: /
    region: oregon

# Define databases here
databases:
  # PostgreSQL database
  - name: my-database
    databaseName: mydb
    user: myuser
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0 # Chấp nhận kết nối từ mọi IP
